/* Omnii Robotics — store data.  GENERATED by tools/build-catalogue.py.
 *
 * The organising axis is deliberately not the one the CubeMars site uses. That
 * site sorts by series (AK, AKE, RI, RO, GL) because there is one brand and its
 * series names mean something inside its own catalogue. Across suppliers a
 * series name means nothing — MyActuator calls its parts RMD-X, Steadywin calls
 * them GIM — so the primary axis is what kind of actuator it is, which is the
 * first real decision an engineer makes and is supplier-independent.
 *
 * `supplier` is a field on the product, never a navigation axis and never a
 * filter. This is how McMaster, Grainger and Misumi work: you find a part by
 * what it does and what size it is, not by who made it. It is also what lets a
 * house-labelled part sit beside a named one without inviting the question.
 *
 * `price` is what we sell for. Dealer cost is deliberately absent — this file
 * is served to browsers. Costs live in internal/costs.json, which is not part
 * of the deployed site.
 *
 * A null in `spec` means we do not have that figure, and the site says so
 * rather than guessing. `ratedAt` is the condition behind the rated figure;
 * "unstated" means the supplier does not publish one, and the compare view
 * will not rank those rows against a stated one.
 */

window.SITE = {
  brand: "Omnii Robotics",
  domain: "omniirobotics.com",
  tagline: "",
  /* omniirobotics.com has no MX records, so nothing addressed to it is
     delivered anywhere. Until mail is set up on the domain this stays the
     Picasso Intelligence address — one that is read — rather than a
     branded one that bounces. It is printed to visitors in the footer and in
     the contact form's failure message. */
  email: "info@picassointelligence.com",
  /* Shared with the Picasso Intelligence site. The contact form posts a
     hidden `site` field so an enquiry can be told apart in the same inbox;
     give this site its own form when that stops being enough. */
  formEndpoint: "https://formspree.io/f/xoeqdwez",
  announce: ["US-based team", "Several suppliers, one comparison", "Engineering support before you buy"],
  year: 2026
};

/* ---- the primary axis: the gearing technology -------------------------- */
/* "when" is the useful half. A buyer who does not already know which
   technology they need is the buyer this site exists for. */
window.TYPES = [
  { id: "qdd", name: "Planetary / QDD", art: "actuator",
    tease: "Backdrivable · low ratio",
    when: "Legged robots and anything that has to feel its own load. A low ratio keeps the joint backdrivable, so torque can be estimated from current instead of measured with a sensor." },
  { id: "harmonic", name: "Harmonic", art: "hollow",
    tease: "Zero backlash · high ratio",
    when: "Arms that must hold a position and repeat it. Strain-wave gearing gives near-zero backlash at high ratio, at the cost of backdrivability and price." },
  { id: "cycloidal", name: "Cycloidal", art: "actuator",
    tease: "High ratio · shock tolerant",
    when: "High ratio where the joint takes impacts. More shock capacity than harmonic in the same envelope, and cheaper, at the cost of a little backlash." },
  { id: "directdrive", name: "Direct drive", art: "frameless",
    tease: "No gearbox · nothing to wear",
    when: "Collaborative joints and test rigs where backlash and gear noise are unacceptable and you can afford the torque penalty." },
  { id: "frameless", name: "Frameless motors", art: "frameless",
    tease: "Rotor and stator only",
    when: "You are designing the housing, bearings and output yourself and want the electromagnetics off the shelf. Outer rotor for torque density, inner rotor for low inertia." },
  { id: "gimbal", name: "Gimbal motors", art: "gimbal",
    tease: "Low cogging · pointing",
    when: "Pointing a camera or a sensor. Smoothness at low speed matters more than torque density." }
];

/* A hollow output shaft is not a gearing technology — RH is harmonic and
   hollow, AKH is planetary and hollow, OT is direct drive and hollow. But it is
   a hard constraint: if the harness cannot pass through the axis the part is
   out, whatever its torque. So it browses like a top-level category and
   filters like the attribute it actually is, and a hollow part appears both
   here and under its own technology. */
window.VIEWS = [
  { id: "hollow", name: "Hollow shaft", art: "hollow",
    tease: "Cable through the axis",
    when: "Arms and wrists where the harness has to pass through the joint instead of looping around it. Cuts across every technology below.",
    match: function (p) { return !!p.hollow; } }
];

/* The order the categories are shown in, across the nav, the home grid and the
   filter chips. Gearing technologies run from the most backdrivable to the
   least geared; the hollow-shaft view sits after the two high-ratio families,
   because that is where most people arrive at it. */
/* The photograph that stands for a maker, or for a technology, on a card.
   Suppliers shoot their catalogues differently — some face-on, some from the
   side — and a row of cards where one part lies on its side and the rest face
   the reader looks like a mistake rather than a set. Pick the face-on shot by
   hand; where a slot is not listed, the code falls back to the dearest part
   that has a photograph, which is right often enough. */
window.HEROES = {
  "siggear:qdd":       "sg-sg-6010hb",   /* compact, face-on; 6010C and D are angled */
  "steadywin:qdd":     "sw-gim8115-9",   /* GIM10015-9 is shot lying on its side */
  "steadywin:directdrive": "sw-ot10025",
  "myactuator:qdd":    "ma-rmd-x2-7",
  "cubemars:qdd":      "cm-ak80-64-kv80"
};

window.BROWSE_ORDER = ["qdd", "harmonic", "hollow", "cycloidal",
                       "directdrive", "frameless", "gimbal"];

/* ---- the secondary axis ------------------------------------------------ */
window.APPLICATIONS = [
  /* Each of these has to select parts, because the cards link to
     select.html?a=<id>. The rule is written out rather than hidden in a list of
     part numbers, so a reader can see why a part is on the page and disagree
     with it. They are bands, not endorsements: an engineer still has to choose.
     `match` runs against a product; `why` is printed above the table. */
  { id: "humanoid", shot: "ma-rmd-x8-120", name: "Humanoid robots", art: "actuator",
    blurb: "Joint modules from wrist to hip. Distal joints are chosen on weight, proximal joints on torque.",
    joints: ["neck", "shoulder", "elbow", "wrist", "hip", "knee", "ankle"],
    why: "Geared joint modules from 2 N\u00b7m up \u2014 wrists at the bottom of the range, hips at the top.",
    match: function (p) {
      return /qdd|harmonic|cycloidal/.test(p.type) && p.spec.torque >= 2;
    } },
  { id: "quadruped", shot: "sw-gim6010-8", name: "Quadruped robots", art: "actuator",
    blurb: "Hip, thigh and knee modules where backdrivability and impact tolerance decide the design.",
    why: "Low-ratio planetary modules, 4 to 60 N\u00b7m. A high ratio would not backdrive, and a leg has to.",
    match: function (p) {
      return p.type === "qdd" && p.spec.torque >= 4 && p.spec.torque <= 60 &&
             (p.spec.ratio || 1) <= 40;
    } },
  { id: "arm", shot: "sw-ot7213", name: "Arms and cobots", art: "hollow",
    blurb: "Repeatability and holding torque first; hollow shafts to route the cable through the joint.",
    why: "Everything with a hollow output shaft, plus the harmonic drives \u2014 the two ways to build an arm that repeats.",
    match: function (p) { return !!p.hollow || p.type === "harmonic"; } },
  { id: "exoskeleton", shot: "sw-wgg7015-8", name: "Exoskeletons", art: "actuator",
    blurb: "Worn on a person, so weight and acoustic noise are constraints, not preferences.",
    why: "Geared modules making at least 4 N\u00b7m for under a kilo. Anything heavier is worn by the wearer.",
    match: function (p) {
      return /qdd|harmonic|cycloidal/.test(p.type) &&
             p.spec.torque >= 4 && p.spec.weight !== null && p.spec.weight <= 1000;
    } },
  { id: "agv", shot: "sw-dd11025", name: "Wheeled robots and AGVs", art: "frameless",
    blurb: "Drive and steering, sized on continuous duty rather than peak.",
    why: "Direct drive and frameless \u2014 no gearbox to wear out under a duty cycle measured in hours.",
    match: function (p) { return p.type === "directdrive" || p.type === "frameless"; } },
  { id: "gimbal-system", shot: "cm-gl60-kv25", name: "Gimbals and sensor pods", art: "gimbal",
    blurb: "Two- and three-axis pointing, where cogging shows up as image jitter.",
    why: "Gimbal motors, and the small frameless motors under 1 N\u00b7m that get built into a pointing head.",
    match: function (p) {
      return p.type === "gimbal" ||
             (p.type === "frameless" && p.spec.torque !== null && p.spec.torque < 1);
    } }
];

/* ---- suppliers --------------------------------------------------------- */
/* Shown on the product page, nowhere else. */
window.SUPPLIERS = {
  cubemars:   { name: "CubeMars" },
  myactuator: { name: "MyActuator" },
  siggear:    { name: "SigGear" },
  steadywin:  { name: "Steadywin" }
};
